<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.1.2.344
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Six Sigma training Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'test@mail.com',
		'to' => 'test@mail.com'
	),
	'fields' => array(
		'custom_U80104' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nom',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nom\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Adresse électronique',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Adresse électronique\' is required.',
				'format' => 'Field \'Adresse électronique\' has an invalid email.'
			)
		),
		'custom_U80099' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Message',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U80090' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Tél. domicile',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U80082' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Société',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U80073' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Adresse pro',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U80094' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Ville',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U80086' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Code postal',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U80078' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Pays',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
